# Generated by Django 5.0.7 on 2025-03-14 15:17

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('guide', '0001_initial'),
        ('hotel', '0001_initial'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(default=None, max_length=30)),
                ('Package_price', models.IntegerField(default=None)),
                ('Total_days', models.IntegerField(default=None)),
                ('Total_nights', models.IntegerField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('Package_description', models.TextField(default=None)),
                ('Package_image1', models.FileField(default=None, max_length=250, null=True, upload_to='package/')),
                ('Package_image2', models.FileField(default=None, max_length=250, null=True, upload_to='package/')),
                ('Package_image3', models.FileField(default=None, max_length=250, null=True, upload_to='package/')),
                ('Slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='Package_name')),
                ('Guid_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='guide.guide')),
                ('Hotel_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='hotel.hotel')),
                ('Transportation_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='transportation.transportation')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=None)),
                ('date', models.DateField(default=None)),
                ('activity', models.TextField(default=None)),
                ('activity_description', models.TextField(default=None)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='package.package')),
            ],
        ),
    ]
