# Generated by Django 5.0.7 on 2025-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_rename_h_name_package_hotel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Package_duration',
        ),
        migrations.AddField(
            model_name='package',
            name='Total_days',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='package',
            name='Total_nights',
            field=models.IntegerField(default=None),
        ),
    ]
