# Generated by Django 5.0.7 on 2025-02-01 15:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_package_duration_package_total_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='Package_name'),
        ),
    ]
