# Generated by Django 5.0.7 on 2025-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_lang', models.CharField(max_length=20)),
                ('g_experience', models.CharField(max_length=20)),
            ],
        ),
    ]
