# Generated by Django 5.0.7 on 2025-01-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=None, max_length=20)),
                ('customer_email', models.EmailField(default=None, max_length=254, unique=True)),
                ('customer_mobile', models.CharField(default=None, max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
