# Generated by Django 5.0.7 on 2025-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('mobile_no', models.CharField(default=None, max_length=10)),
                ('birth_date', models.DateField(default=None)),
                ('gender', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
