# Generated by Django 5.0.7 on 2025-02-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0004_package_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='package.package')),
            ],
        ),
    ]
