# Generated by Django 5.0.7 on 2025-02-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_package_slug'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.AddField(
            model_name='schedule',
            name='total_days',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='package.package'),
        ),
    ]
